### ISSUE TITLE
Deprecate mmforc and the mechanism to execute mmf as a k8s job.  

### ISSUE THREAD

**Issue by sawagh** [GoogleCloudPlatform/open-match#105]
This change should do the following:
- Deprecate mmforc 
- Remove the mechanism to run mmfs as k8s jobs
- Explore options to run evaluator once mmf returns

**Comment by sawagh** [comment]
Will take this issue up for 040wip.

**Comment by calebatwd** [comment]
There's a discussion here around the evaluator and how to create the synchonizing context

**Comment by sawagh** [comment]
This is deprecated. 

https://github.com/GoogleCloudPlatform/open-match/commit/4cbee9d8a7f5ccbbee15222e56fbde176fc3710c
