### ISSUE TITLE
Proposal: Use go mod compatible semver for release tags.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#110]
Golang is now mid stage at rolling out go modules. It'll be the default in the next version ~6 months away. An important requirement that go mod enforces is the use of semantic version tags for releases. This means if a game studio wants to depend on Open Match 0.4.0 the recommended way in Go 1.13+ will be run `go get -u github.com/GoogleCloudPlatform/open-match@v0.4.0`. Using branches and tag formats that are not vX.Y.Z will fail. There is a fall back for repositories that do not follow this standard which involves using the git commit hash instead which is ugly. See https://github.com/golang/go/wiki/Modules#version-selection for more information.

I'd like to propose we should start using semver starting with the 0.4.0 release. This change is tied with proposal, https://github.com/GoogleCloudPlatform/open-match/issues/97 which allows Open Match to confirm with typical Github workflows.

**Comment by joeholley** [comment]
I like this idea.  There was some guidance I read when choosing the current tag format that had recommended having the '-alpha' after it for some reason.  I can't remember what it was any more, though.

**Comment by jeremyje** [comment]
We've had discussions with Unity that ended up coming out that using "alpha" is confusing because alpha means different things to each company. At some point GCP had this policy, https://cloudplatform.googleblog.com/2014/10/new-release-phases-for-google-cloud.html.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/pull/106
