### ISSUE TITLE
Choose the form of the requests/responses for MMFs running the gRPC harness

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#121]
It doesn't have to be the final one, but we should definitely have a pass before it ends up in the repo, as it doesn't conform to any of Jeremy's changes or have any of Caleb's input.  So far, what we have right now is:

```proto
message MmfSpec {
    string name = 1;  // Arbitrary developer-chosen, human-readable string.  Optional.
    string host = 2;  // Host or DNS name for service providing this MMF.  Must be resolve-able by the backend API.
    int32 port = 3;   // Port number for service providing this MMF.
    enum Type {
        // Generic serving types.
        GRPC = 0;
        REST = 1;
        // Knative types will be KNATIVEREST, KNATIVEGRPC, etc.
 
        // Deprecated types
        K8SJOB = 7;
    }   
    Type type = 4;    // Type of MMF
}
 
message CreateMatchRequest {
  MatchObject matchobject = 1;
  MmfSpec mmfspec = 2;
}
 
message ListMatchesRequest {
  MatchObject matchobject = 1;
  MmfSpec mmfspec = 2;
}
```
The `MatchObject` message didn't change, so I didn't include it here.

The Backend API then generates the necessary database record keys and calls the `function` gRPC API at the `host` and `port` it reads from the `MmfSpec` message:
```proto
service Function {
 
  // The assumption is that there will be one service for each MMF that is 
  // being served.  Build your MMF in the appropriate serving harness, deploy it
  // to the K8s cluster with a unique service name, then connect to that service
  // and call 'Run()' to execute the fuction.
  rpc Run(messages.Arguments) returns (messages.Result) {}
 
}
```

Its messages look like this, and definitely need to get updated to be in line with Jeremy's changes.
```proto
// Messages for gRPC-served matchmaking functions.
 
// The message for passing in the per-request identifiers
// to a matchmaking function; used so it knows which records to
// write/update in state storage.  Internal to Open Match; this is populated by
// the Backend API and sent to your gRPC-served MMF.
message Request {
    string profile_id = 1;  // Developer-chosen profile name, a copy of the MatchObject name.
    string request_id = 2;  // Per-request generated unique ID, by convention XID.
    string proposal_id = 3; // Intermediate result proposal ID. by convention, the string 'proposal.' prepended to the result_id. 
    string result_id = 4;   // Final result ID. By convention, request_id.profile_id
    int64 timestamp = 5;    // Reserved for future use.
}
 
// The message for passing all the necessary arguments to a 
// matchmaking function.
message Arguments{
    Request request = 1;
    MatchObject matchobject = 2;
}                                     
```

So, let me know how we want it to look and I'll get to work on updating it for inclusion in the 0.4.0 RC.

**Comment by jeremyje** [comment]
This looks reasonable as a stop gap between what's there now and where we want to take OM. I think we should move forward with this in 0.4.0 to get a good baseline.

The only things that I'd optionally say is drop the messages.Result (use grpc error codes instead) and we are going to kill off the K8SJOB type so let's not expose it.

**Comment by joeholley** [comment]
Cool, I'll leave K8SJOB out.  I'll let you guys take out the Result later when you're ready to; I have code that relies on being able to parse particular failure conditions that doesn't map to gRPC error codes so I'll have to figure that out afterwords and refactor my examples.

**Comment by sawagh** [comment]
@joeholley - when i started the PR to deprecate mmforc (which eventually i don't think will be completely deprecated), here is the branch I pulled your GRPC changes into:
https://github.com/sawagh/open-match/tree/deprecatemmforc

The test client / harness changes are identical - I did modify some of the protos - and did the merging of the backend client API implementation with the protos. Do glance at the changes (specially the proto). Since you are merging the GCD demo branch into 0.4.0, I ll sync your checkin to continue the evaluator changes in 0.5.0

**Comment by joeholley** [comment]
@sawagh - I tried to have a look at it, but it seems to be based on the code form before the gdcbackports branch was cleaned up for merge, so I'm not exactly sure what I'm looking for.
Here's what I see when comparing against the latest gdcbackports branch:
https://github.com/GoogleCloudPlatform/open-match/compare/gdcbackports...sawagh:deprecatemmforc?diff=split&w=1

I see that Function was renamed to MatchFunction: that is fine with me if fine with @calebatwd , I think Function was the name from his code: https://github.com/GoogleCloudPlatform/open-match/blob/grpc-functions/api/protobuf-spec/function.proto

If there are other parts of the diff in particular you want me to look at, I'm happy to, just flag the particular file diffs :)
