### ISSUE TITLE
gRPC MMF harness should be 'go get'-able

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#125]
It's in the examples directory now, but we should work towards having the golang gRPC MMF harness in the `pkg` directory.  This will likely depend on https://github.com/GoogleCloudPlatform/open-match/issues/122

**Comment by jeremyje** [comment]
This mostly depends on, https://github.com/GoogleCloudPlatform/open-match/issues/97. internal/... vs pkg/... is mostly a cosmetic fix. I don't believe go has any enforcement on what directory you link from. But since none of the code is in master you cannot access the harness anyway.

**Comment by ihrankouski** [comment]
Actually internal/ package is only importable by the packages that share the same root with it.
https://golang.org/doc/go1.4#internalpackages
