### ISSUE TITLE
Proposal: openmatch.dev as the main website URL.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#127]
We secured multiple domains for Open Match and we are getting close to publishing a website for it. Currently the Github repository is `github.com/GoogleCloudPlatform/open-match`. For go get, this is problematic because hyphenated last paths are not allowed, see https://github.com/GoogleCloudPlatform/open-match/issues/114 for details.

Given this restriction and the desire to keep this as consistent as possible I'd like to propose http://openmatch.dev/ as the primary URL for the website.

We can also have http://open-match.dev/ as well but we'll need to workaround the tail hyphenation problem that open-match does with golang.

**Comment by joeholley** [comment]
I agree with all your points.  Maybe run it past Micah as when he spoke to branding they had recommended we not use a concatenated name, he could have more details if there's anyone who needs to sign off on this.

**Comment by joeholley** [comment]
Also would be awesome if we could make the decision before Next so I can put it in slides :)

**Comment by micah-gcp** [comment]
The external naming is Open Match with a space, so open-match.dev is the website that will be used for any user facing content. For developers, it's acceptable to use openmatch.dev if we have technical reasons not to use open-match.dev. Both URLs will point to the same place, and we can be clear in the documentation that openmatch.dev must be used in the code. Does that sound fair?

**Comment by jeremyje** [comment]
That sounds fine to me. It's possible to have `go get open-match.dev/open-match` as the command to depend on the repository but it just complicates package name consistency because a package name cannot have a dash in it. Another option is to have `go get open-match.dev/openmatch` as the vanity url.

**Comment by micah-gcp** [comment]
We now have development.openmatch.dev, www.openmatch.dev, openmatch.dev, development.open-match.dev, www.open-match.dev, and open-match.dev live. The development URLs point to the new website, and the others simply redirect to the github project. We can switch to the live site at any time now.
