### ISSUE TITLE
Rename the example functions to remove the mmlogic name from them

### ISSUE THREAD

**Issue by sawagh** [GoogleCloudPlatform/open-match#131]

**Comment by sawagh** [comment]
@jeremyje  - please assign this to me :)

**Comment by joeholley** [comment]
is there a plan to  label these or organize them into another directory such that everyone understands which examples use the MM logic API and which ones don't without having to go in and read the code?

**Comment by sawagh** [comment]
I think for now, the examples we provide should just use the MMLogic API to access player data. Although the MMF can access redis directly, should our examples encourage that pattern through examples? The current manual example exposes the data access logic of the mmlogic in the example - with comments around each access indicating that the mmlogic api should be used instead. 

I think our basic example folders can simply be under the language folder without the 'mmlogic' in the name. Once we have additional examples, a README - and the documentation either in the top level folder - or the website detailing what the example does would anyways be necessary as the folder names may not suffice to disambiguate between each.

**Comment by joeholley** [comment]
SGTM, we should also mark the manual sample as deprecated in the next changelog too if we're going to remove it.

**Comment by sawagh** [comment]
This issue is no longer valid since only serving harness examples are now present in 0.5
