### ISSUE TITLE
Remove manual request/response stats.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#144]
There's a lot of lines in our gRPC endpoints that are gathering metrics manually for requests/responses.

```golang
stats.Record(fnCtx, FeGrpcRequests.M(1))
stats.Record(fnCtx, FeGrpcErrors.M(1))
```

This isn't necessary because there's an stats collector interceptor that's already installed in the gRPC servers do this work automatically.

```golang
s := FrontendAPI{
		pool: pool,
                // Enables automatic stats collection!
		grpc: grpc.NewServer(grpc.StatsHandler(&ocgrpc.ServerHandler{})),
		cfg:  cfg,
	}
```

We should so verify that the auto stats are properly emitted and should be ingestible by the Prometheus/Grafana.

The dashboards are here, https://github.com/GoogleCloudPlatform/open-match/blob/master/install/helm/open-match/dashboards/grpc.json

**Comment by joeholley** [comment]
They were originally there because you cannot tag (label, in Prometheus terms) the metrics emitted by the gRPC library.  So when we want to be able to segment call successes and failures by additional, open-match specific context, we're going to need these.  In particular, it seemed pretty likely we'd want to tag every success/failure in the backend call chain with the name of the MMF involved, since that's going to be the customization point the developer is actually interfacing with.

**Comment by jeremyje** [comment]
Can you provide some details like what tags are interesting here. Prometheus/grafana screenshots for example.

**Comment by joeholley** [comment]
These aren't implemented yet.  If you feel very strongly, go ahead and remove these and I'll go back and re-add them later when ready to implement those metrics.

**Comment by jeremyje** [comment]
We shouldn't remove the code if you're just going to add it back. I'm interested in what you want instrumented though and I think we should explore more clean/concise ways to get what you want. The reason this is a bug is because adhoc metrics counting like this is a big anti-pattern. What ends up happening is refactorings and mistakes will make the metrics untrustworthy over time. This becomes problematic once the metrics eventually are key'ed off of alerts that might page someone.

In Prometheus there's re-write labeling and a bunch of other tricks you can do to make things tagged appropriately but it's important to understand what we are trying to measure and why.

**Comment by joeholley** [comment]
I'm not terrifically experienced in Prom/Grafana metrics so if you feel it's an anti-pattern, go ahead and pull these.  We'll find another way to track this information after the 0.7 release.
