### ISSUE TITLE
REST Implementation

### ISSUE THREAD

**Issue by yfei1** [GoogleCloudPlatform/open-match#196]
Open Match should provide REST APIs on top of its grpc services. The implementation can be break down into three steps.

1. Add google.api.http annotation to the .proto files for REST definitions. Done in #183
2. Generate reverse-proxy to convert any calls to REST APIs into grpc calls
3. Write entrypoints for the REST proxy and modify kubernetes config file to expose REST ports accordingly.

**Comment by joeholley** [comment]
Is there a way we can we make the choice between REST or gRPC set via config?

**Comment by yfei1** [comment]
> Is there a way we can we make the choice between REST or gRPC set via config?

the current REST implementation only adds a gateway layer on top of the gRPC service so there won't be any overhead if we do gRPC call directly, the framework is still built upon gRPC service
