### ISSUE TITLE
issues with release process

### ISSUE THREAD

**Issue by Laremere** [GoogleCloudPlatform/open-match#269]
Writing down all of the issues I encounter here:
-" Open a document for a draft release notes." link leads to 404.
-"The link resolves to, v{version}...master."  It resolves to v{PREVIOUS version}...master.  That whole sentence seems weird, just remove?  The instructions seemed good enough.
- The commits since last release links to commits, not the PRs.  Not all commits specify their PR.
- Search for merged pull request tagging should include " is:merged " to exclude pull requests which were abandoned.
- Unclear if all of the versions should be updated for release candidates.  Should the RC suffix be included in all of them?  I skipped the README.md for the RC.
- Skipped tagging, because the tags aren't specified.
- Tagging shouldn't be the job of the person doing the release.

- Why is it that one of the first steps is to open the release notes to start writing a draft, then later it says to create a draft release with the same template?
- cloudbuild.yaml needs to be included in places version number needs to be set.

- "git checkout master && git pull master && git rev-parse HEAD" is not the git command we want.  Instead: "git fetch upstream && git rev-parse upstream/master"
- "take note of the hash in git master" take note for what?
- I don't have permission to run post submit trigger.  However, it looks like it triggered automatically?
- Making the release notes is a lot of work, though you're working on this for 0.6 I think?

Post submit failed with: "Deploy: Deployment Configs": / [0 files][ 0.0 B/ 13.3 KiB] 
AccessDeniedException: 403 205790239254@cloudbuild.gserviceaccount.com does not have storage.objects.delete access to open-match-chart/install/yaml/master-latest/01-redis-chart.yaml.

.... I accidentally hit enter and made a release instead of it being a draft.

**Comment by Laremere** [comment]
Ok, I managed to remove the accidentally submitted release by editing and pushing it back to draft, then deleting the tag.

**Comment by jeremyje** [comment]
> -" Open a document for a draft release notes." link leads to 404.

Was this because it wasn't checked in? This seems to work against the repository now. Was there a specific way you were viewing it?

**Comment by Laremere** [comment]
Try the link in the actual issue: https://github.com/GoogleCloudPlatform/open-match/issues/266
It's broken because the link is relative, and the issue is not in the same folder as the template.

**Comment by Laremere** [comment]
> > The commits since last release links to commits, not the PRs. Not all commits specify their PR.
> 
> Going forward they should. There might be a few in v0.5.0 that do not but I think that's ok, just ignore. Is there in particular blocker here?
I think that will be fine.

> > Unclear if all of the versions should be updated for release candidates. Should the RC suffix be included in all of them? I skipped the README.md for the RC.
> 
> TBH I don't know we should do it and see what happens.

That's what I've done for this release.

> > Tagging shouldn't be the job of the person doing the release.
> 
> This happens when you create the github release. This will be automated later. There's no `git tag` command in the instructions today.

Sorry, I meant applying labels, not tagging.

**Comment by Laremere** [comment]
[] `make delete-gke-cluster create-gke-cluster push-helm sleep-10 install-chart install-example-chart`
Failed the first time I ran it, because the sleep wasn't long enough.

**Comment by Laremere** [comment]
Error from failed install:
`/usr/local/google/home/sredig/Desktop/open-match/build/toolchain/bin/kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-rule created
echo "Waiting for Tiller to become ready..."
Waiting for Tiller to become ready...
/usr/local/google/home/sredig/Desktop/open-match/build/toolchain/bin/kubectl wait deployment --timeout=60s --for condition=available -l app=helm,name=tiller --namespace kube-system
deployment.extensions/tiller-deploy condition met
sleep 10
/usr/local/google/home/sredig/Desktop/open-match/build/toolchain/bin/helm upgrade --install --wait --debug open-match install/helm/open-match \
	--namespace=open-match \
	--set openmatch.image.registry=gcr.io/sredig-gaming-test \
	--set openmatch.image.tag=0.5.0-rc1-be55bfd
Error: could not find a ready tiller pod
Makefile:272: recipe for target 'install-chart' failed
make: *** [install-chart] Error 1
`

**Comment by Laremere** [comment]
> You'll need to adjust the path to the install/yaml/install.yaml and install/yaml/install-example.yaml in your local clone since you haven't published them yet.

This should say to use the release yamls, not the install yaml.

**Comment by jeremyje** [comment]
> Failed the first time I ran it, because the sleep wasn't long enough. Is there a way to just wait until the condition is ready instead of sleeping?

The makefile already has `$(KUBECTL) wait deployment --timeout=60s --for condition=available -l app=helm,name=tiller --namespace kube-system` but it doesn't appear to be effective.

**Comment by Laremere** [comment]
Well, it worked the second time, so idk.

**Comment by Laremere** [comment]
#269 resolved most of this.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/issues/250 will address the remainder of release issues.
