### ISSUE TITLE
API Changes for Open Match 0.6.0

### ISSUE THREAD

**Issue by sawagh** [GoogleCloudPlatform/open-match#279]
As we plan the road map to Open Match 1.0, we are revisiting the Data Model and the API surface exposed by Open Match and are proposing modifications to these to facilitate future feature work to achieve scale and production readiness. 

The goal of this proposal is to solidify the concepts understood by Open Match, clearly identify and define the APIs exposed (and thereby identify the concepts / features that are beyond the scope of Open Match). The proposal also states some design principles and refactors the existing API to achieve those. 

The proposal focuses on the API modifications while providing some details on the features these changes will achieve. Separate proposals / issues will be created for other significant related features. 

Please go over the proposal and add your comments:

[Open Match API Change Proposal](https://docs.google.com/document/d/1dm7hgE_M5Au_QF2ingEYjTqsHrWg9n6-cOx5Jv7UM-I/edit?usp=sharing)

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/pull/322 added the new API.
