### ISSUE TITLE
docs/governance/templates/release.sh is brittle

### ISSUE THREAD

**Issue by Laremere** [GoogleCloudPlatform/open-match#281]
It's only run during releases, so I imagine it's easy to break.  Eg, if the list of images changes at all, releases will need to cherrypick a fix to the script.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/issues/250 will address this.

**Comment by jeremyje** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/open-match/issues/250
