### ISSUE TITLE
Evaluate switching various object IDs from UUIDv4 to xid

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#32]
https://github.com/rs/xid

This is an internal representation thing - shouldn't have any impact outside of the core components, or in any custom functions/evaluators/backend client/frontend clients.  Will drop the string size for the unique IDs from 36 characters to 20 characters, a pretty significant memory savings in Redis.  We'll also be passing around less data this way, and it should help with the 64-character Job name limit in Kubernetes when kicking off evaluators and MMFs as well.

**Comment by scrypter** [comment]
I'm out of the country and away from my computer till Sunday, but I'd love to take a stab at this one. You mention evaluate switching to xid: are there any specific scenarios you'd like benchmarked to determine if the switch should be made?

**Comment by joeholley** [comment]
The major needs that UUID meet for us right now are: 

- reasonable performance
- sufficient randomness that we're never concerned about collisions
- generation is generally pretty distributed across the possibility space (since the IDs are used as database keys, this will become important if/when we support sharded state storage - we want the default key generation for OM to already be distributing the keys nicely to avoid hot spotting).
- available implementations in all the major languages we think people might use to connect to OM (C++, C#, python, golang are critical, php, perl, ruby, nodejs are important, other languages are nice-to-have)

If XID can meet the requirements, then it will just be a matter of swapping it out everywhere in a branch and making sure everything still works ok.

**Comment by scrypter** [comment]
After doing some research, what I've been able to find is:

> - reasonable performance  

Based on the benchmarks presented in [the golang repo](https://github.com/rs/xid), [the .Net repo](https://github.com/Yortw/Xid.Net), and [a jvm repo](https://github.com/kolotaev/ride), it would appear Xid is capable of performing as well as UUID. The benefit is seen more when generating Xid distributed across multiple cores given that it is a lock-free UUID generator.

> - sufficient randomness that we're never concerned about collisions

 [Unicity guaranteed for 16,777,216 (24 bits) unique ids per second and per host/process](https://github.com/rs/xid). Xid is similar to UUIDv1 in that it combines a machine identifier, time, and random element to guarantee uniqueness. The difference is that there is an additional consistent component of an Xid as well, the process identifier.

> - generation is generally pretty distributed across the possibility space (since the IDs are used as database keys, this will become important if/when we support sharded state storage - we want the default key generation for OM to already be distributing the keys nicely to avoid hot spotting).

Generation is not distributed evenly. Given that Xid has a component that's tied to time, it [changes monotonically](https://docs.mongodb.com/manual/core/hashed-sharding/#hashed-sharding-shard-key). Generated Xid alone would [increase the likeliness of distributing inserts to a single shard](https://docs.mongodb.com/manual/core/sharding-shard-key/#shard-key-monotonic). Per the mongoDB documentation and [Redis support for hash partitioning](https://docs.mongodb.com/manual/core/sharding-shard-key/#shard-key-monotonic), I think hot spotting could still be avoided. I think a fair call out would be a warning for those wanting to use something other than the default state storage of the potential risks that are incurred by selecting a persistence layer that doesn't support hashed shard keys if this change were made.

> - available implementations in all the major languages we think people might use to connect to OM (C++, C#, python, golang are critical, php, perl, ruby, nodejs are important, other languages are nice-to-have)  

Libraries I've found and tested so far:
### Critical
- [C++](https://github.com/iCyberon/pg_xid) (Technically this is a C implementation specific for adding support to Postgres, but at least provides a reference)
- [C#/.NET](https://github.com/Yortw/Xid.Net)
- [python](https://github.com/graham/python_xid)
- [golang](https://github.com/rs/xid)

### Important
 - none

### Nice-to-have
 - [jvm](https://github.com/kolotaev/ride)

**Comment by joeholley** [comment]
Thanks for all the hard work!  Definitely looks like a great fit.  Do you want to do the PR as well?

**Comment by scrypter** [comment]
Definitely, I'll be doing it today.

**Comment by joeholley** [comment]
Messed with this, seems to be working fine.  Will get a 0.3.0 branch together next week and will update your PR to target that branch so it can be in the release candidate (we try to avoid merging to master between versions unless it's a bug fix :D )

**Comment by tomd8451** [comment]
Good to know, I'll keep that in mind for future PRs.

**Comment by scrypter** [comment]
Good to know, I'll keep that in mind for future PRs.
