### ISSUE TITLE
Why redis and not postgresql (cockroachdb)

### ISSUE THREAD

**Issue by fire** [GoogleCloudPlatform/open-match#33]
Wondering?

Supporting cockroachdb would allow clustering.

**Comment by joeholley** [comment]
Interesting, would love to get more information.  What features would you find most useful in CRDB?  Are you interested in clustering for the HA or scalability?  How important is persisting the state data after the player session for you?

**Comment by fire** [comment]
Cockroachdb can be slow compared to memory access, I was seeing like 60,000 operations on redis per core from a test a few years ago. You'll probably need to keep the state in memory and only save to the cockroachdb for the record. Although cockroach does simplify distributed state because it is in SQL terms Serializable Snapshot Isolation.

This means cockroachdb is interesting for high availability, scalability is probably faster in memory and batched. 

HA: It's easier to provide HA on cockroachdb compared to a single redis docker or a master slave postgresql system.

Scaling: It may be possible to save the reports on the open match instances and submit the data as a group.

I am interested in the match making and the things that allow the match making to function for a first pass. So things like leader boards and given two team of players give a ranking.

From experience doing statistical capture and analysis requires a lot more compute and storage. Those can A) be summarized B) statistically sampled but that I think is out of scope for this system, although this system should provide a way to send the packet of game data somewhere after changing for example the leader board.

**Comment by joeholley** [comment]
Yeah, that makes sense, and I agree it's out-of-scope for Open Match. I also agree that being able to egress results out of Open Match is an important feature and we'll continue to keep that front-of-mind as we develop.
