### ISSUE TITLE
New website issues

### ISSUE THREAD

**Issue by micah-gcp** [GoogleCloudPlatform/open-match#360]
The new website has a few issues to sort out:

- On the [main page](https://development.open-match.dev/site/), the Release tab links to app-spot.com URLs and should use the vanity URLs. We should scrub for any app-spot.com URLs across all content.

- There is a Read Me under Perfect Match on the main page that probably shouldn't be there (it links to the Twitter feed).

- The documentation page should explicitly call out that advanced editing steps are required for changes on the landing page.

- The Releases button on the main page redirects to a nonexistant godoc URL.

- The main page says Flexible, then Scale, and Perfect Match next. It should say Scalable and Quality Matching to keep the same present participle, and avoid the use of "perfect" which is undefinable.

- The Pull Requests link at the bottom of the main page under Contributions Welcome redirects to a nonexistent godoc URL.

- The github icon in the very bottom right corner of the main page should link to the vanity URL.

- The [Community page](https://development.open-match.dev/site/community/) has a dark font for the links, making them appear invisible.

- Should the github link in the top banner on the main page link to the vanity URL instead?

**Comment by jeremyje** [comment]
The vanity url is just for go not the github repository itself. I've address these issues in https://github.com/GoogleCloudPlatform/open-match/pull/364
