### ISSUE TITLE
Mmforc idle memory leak

### ISSUE THREAD

**Issue by calebatwd** [GoogleCloudPlatform/open-match#44]
Running vanilla v0.1 mmforc shows a pretty aggressive memory leak of ~250MB/hr.

![image](https://user-images.githubusercontent.com/7191591/49243831-30efe300-f3c3-11e8-81a3-befa9ec50798.png)

**Comment by joeholley** [comment]
Going to mark this as wonfix for now as I can't reproduce it; someone please re-open if you can with some instructions.

Thanks!
