### ISSUE TITLE
Move builds to a 'base' image and associated changes

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#45]
Since we want public images in 0.3.0, we'd like to start the work to un-jank-ify the `Dockerfile`s and `cloudbuild.yaml` files.  This should be doable by anyone with a decent understanding of docker, cloudbuild, and kubernetes (to test that the results work correctly).  Basically:

1. First thing to know: this should probably come after the issue to evaluate using configmaps for the OM config.  Removing the need to include the config file in the images will be necessary to keep from having to have base images for languages other than golang.
1. For all the golang container images that use internal modules (this will be all components, not necessarily all examples or test clients, tho), make a `cloudbuild.yaml` and `Dockerfile` that builds off the golang base image and adds the `internal` directory.  After making this new 'open match base image', the `Dockerfile` and `cloudbuild.yaml` file to build it should be the only ones left in the repo root, I think.
1. Refactor all the other `cloudbuild.yaml` files and `Dockerfile`s in the repo root to be in the directories of the associated components, examples, and test clients.
1. [Optional] Probably have some make script or the like to run 'all' the builds that can be run from the repo root.

**Comment by scrypter** [comment]
While I'm taking a stab at [Issue 54 to document local build and development](https://github.com/GoogleCloudPlatform/open-match/issues/54), is it cool if I tackle this at the same time. I found myself starting to make these kinds of refactors while looking at mirroring the Agones local development with Make setup, and it started to feel a little bigger than just documentation.

**Comment by joeholley** [comment]
This will be included in 0.4.0 release scheduled for late Feb 2019.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/pull/129
https://github.com/GoogleCloudPlatform/open-match/pull/98
Resolves this.
