### ISSUE TITLE
Local development instructions

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#54]
For folks that need local development of Open Match, instructions and possibly a make file for Kubernetes in Docker (like the [one Agones has](https://github.com/GoogleCloudPlatform/agones/blob/master/build/README.md#running-a-test-kind-cluster)) or even just minikube would be great.  Just instructions on getting everything compiled and deployed into a local environment is all that's needed, I think.

**Comment by scrypter** [comment]
Is anyone working on this, or is it ok if I pick this up? If it's available, I can work on it today.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/pull/100 is a stab at this.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/tree/040wip#compiling-from-source are the instructions.
