### ISSUE TITLE
Frontend API Kubernetes Ingress guide

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#56]
Had three different users ask about proper configuration of an Kubernetes nginx ingress for the Frontend API.  Would be great if someone can add a quick guide to the important annotations and such required to get this set up correctly for the HTTP2 gRPC Frontend API service.  Could optionally cover more broadly the topic of making the Frontend API public, and should _definitely_ cover what use cases require the (relatively complex) nginx ingress over a simple public service configured using the `type: LoadBalancer`.

**Comment by jeremyje** [comment]
We have a grpc http proxy this is obsolete.
