### ISSUE TITLE
Watcher exponential backoff + jitter 

### ISSUE THREAD

**Issue by joeholley** [GoogleCloudPlatform/open-match#59]
The watcher functions in internal/statestorage/redis/redispb/matchobject.go and internal/statestorage/redis/redispb/player.go are both currently 'query every 2 seconds' and are going to generate a lot of the overall redis load on OM.  It would be better to have them set up with (configurable) exponential backoff & jitter.  There are a few implementations of exp bo + jitter as golang modules, we need someone to evaluate them and then test the one we pick.

**Comment by ihrankouski** [comment]
Looks like the most popular implementation of ExpBO on Github is https://github.com/cenkalti/backoff.
I'm currently playing with it inside those two Redis watchers, will probably open a PR soon.

**Comment by joeholley** [comment]
This will be included in 0.4.0 scheduled for late Feb 2019.
