### ISSUE TITLE
Change Open Match gRPC API to be structured like a typical gRPC server.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#90]
Quick Example of the Pattern

```proto
message CreateMatchRequest {
  messages.MatchObject match = 1;
}

message CreateMatchResponse {
  messages.MatchObject match = 1;
}

service Backend {
  rpc CreateMatch(CreateMatchRequest) returns (CreateMatchResponse) {} 
}
```

**Comment by jeremyje** [comment]
You can see the proposed diff here: https://github.com/GoogleCloudPlatform/open-match/compare/040wip...jeremyje:requestresponse?expand=1

**Comment by calebatwd** [comment]
This allows us to allow diverging contracts and keep a very clean pattern. [thumbs up]

**Comment by jeremyje** [comment]
Also some of the messages like Result should be removed. gRPC already has a proper error management, https://jbrandhorst.com/post/grpc-errors/ is a good article.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/pull/150
