### ISSUE TITLE
Proposal: After 040wip release we should do development directly on master branch.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/open-match#97]
Typically in a git repository the master branch is where active development occurs for cutting a new release. This is outlined in the [Github flow](https://guides.github.com/introduction/flow/) process. In addition, once a version is cut there's a few things that should happen,
 1. The version is tagged using a [semantic version](https://semver.org/) complaint tag like v1.0.0. See proposal, https://github.com/GoogleCloudPlatform/open-match/issues/110.
 1. A release branch is created for v1.0.x releases. Example, release-v1.0.0.
 
Challenges for the old pattern:
 1. It's surprising behavior to `go get -u github.com/GoogleCloudPlatform/open-match` and not really know what version you're working with.
 1. go get will only read from master. This means consumers of Open Match will be pinned to a very old version of Open Match.
 1. Other tools make assumptions on repository layout that we currently break away from, like godoc.org, goreportcard.com, 

not branches. It has support to read from [semver tags](https://golang.org/cmd/go/#hdr-Download_modules_to_local_cache) against master branch now.

How do we get there?
 1. Merge in (forcefully or not) 040wip changes into master.
 1. Tag the commit with v0.4.0
 1. Create a branch called release-v0.4.0
 1. New pull requests will always be accepted into master. If a change is required into a patch release then 2 PRs are necessary, master and the release branch for the hotfix.

With this change we'll be modeling the development pattern that [Kubernetes](https://github.com/kubernetes/kubernetes) does.

**Comment by sawagh** [comment]
Lets discuss this - and the next steps. Going down this route would mean creating a release branch for 0.4.0 - along with merging 040wip into master.

**Comment by calebatwd** [comment]
👍
